### ISSUE TITLE
NEW TASK - User Management system

### ISSUE THREAD

**Issue by ethanux** [mictseta-recruitment-system/mictseta_recruitment_system#13]
# create user groups
1. Super User
2. manager/HR User
3. Default User

## Create Super User
 - super user can give permission to other users
 - super user can ban other users
 - super user can Read,Create, Delete, Update any user information,
 - super user can Read,Create, Delete, Update any  jobs 
- super user can Read,Create Delete Update any user Posts and Comments 

## Create Manager/ HR User
  - manager user can see other Users
 - manger user can Update, Read any user information
 - manager user can  Read, Create, Update  Jobs information created by the manager
 - manager user can Read, Update, Create any user Post and comments

## Create Default User (applicant/client )
- Default user can Create, Update,Delete their profile
- Default user can Read, Update, Create, Delete their profile Post and comments
- Default user can Read and Apply For any jobs

**Comment by ICTPass2002kgao** [comment]
And there should be a guest user
That can only read but not write
